name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version type'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  release-pr:
    name: "Prepare release PR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-bump
      - run: cargo install cargo-get
      - run: |
          git config user.name "Christoph Wulf"
          git config user.email "christoph@wulf.technology"
      - name: Update the version
        id: update_version
        run: |
          cargo bump ${{ github.event.inputs.version }}
          cargo generate-lockfile --offline # ensure the version is updated in Cargo.lock as well
          echo "version=$(cargo get package.version)" >> $GITHUB_OUTPUT
      - name: Create pull request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: release/${{ steps.update_version.outputs.version }}
          title: "Release ${{ steps.update_version.outputs.version }}"
          commit-message: "Release ${{ steps.update_version.outputs.version }}"
          body: "Updates version to ${{ steps.update_version.outputs.version }}"
          base: main
          labels: release, ${{ steps.update_version.outputs.version }}
          token: ${{ secrets.KIEK_RELEASE_PAT }}
